default:
  tags:
    - noprox

variables:
  CLI_NAME: pnapctl
  ARTEFACT_FOLDER: build
  ARTEFACT_DIST_FOLDER: dist
  TEST_COVERAGE_FOLDER: test/coverage

stages:  
  - test
  - dev-build
  - prod-build
  - dev-portal-deploy
  - prod-portal-deploy

.go-cache:
  variables:
    GOPATH: ${CI_PROJECT_DIR}/.go
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod/

test:
  extends: .go-cache
  stage: test
  image: registry.gitlab.com/phoenixnap/docker/golang:1.17.1
  script:
    - make test-coverage COVERAGE_DIR=${TEST_COVERAGE_FOLDER}
  artifacts:
    when: always
    reports:
      junit: ${TEST_COVERAGE_FOLDER}/report.xml


.build:
  extends: .go-cache
  stage: build
  only:
    - master
    - tags
  image: registry.gitlab.com/phoenixnap/docker/golang:1.17.1
  script:
    - make build-and-pack ENVIRONMENT_NAME=$CI_ENVIRONMENT_NAME
  artifacts:
    when: on_success
    paths:
      - ./${ARTEFACT_FOLDER}/$CI_ENVIRONMENT_NAME/${ARTEFACT_DIST_FOLDER}

.portal-deployment:
  image: registry.gitlab.com/phoenixnap/platform-api/apigee-automation:0.0.6
  only:
    - master
  script:
    - /automation/upload_assets.py --folder ./${ARTEFACT_FOLDER}/$CI_ENVIRONMENT_NAME/${ARTEFACT_DIST_FOLDER} --portal "$APIGEE_PORTAL" --org $ORG_NAME --username $APIGEE_USER --password $APIGEE_PASSWORD

portal-dev-deploy:
  extends: .portal-deployment
  stage: dev-portal-deploy
  environment:
    name: dev

portal-prod-deploy:
  extends: .portal-deployment
  stage: prod-portal-deploy
  environment:
    name: prod
  only:
    - tags

build-dev:
  extends: .build
  stage: dev-build
  environment:
    name: dev

build-prod:
  extends: .build
  stage: prod-build
  environment:
    name: prod
  only:
    - master
