image: docker:latest
services:
  - docker:dind
  
variables:
  CLI_NAME: pnapctl
  ARTEFACT_FOLDER: build

stages:  
  - test
  - dev-build
  - prod-build
  - dev-portal-deploy
  - prod-portal-deploy

.go-cache:
  variables:
    GOPATH: ${CI_PROJECT_DIR}/.go
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod/

test:
  extends: .go-cache
  stage: test
  image: golang:1.13.1
  before_script:
    - apt-get install curl git
    - go mod download
    - go get "github.com/golang/mock/mockgen"
    - go get -u "github.com/jstemmer/go-junit-report"
  script:
    #-vet-off is required due to failures in using gcc 
    - go test ./... -v -vet=off 2>&1 | ${GOPATH}/bin/go-junit-report > report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml


.build:
  extends: .go-cache
  stage: build
  only:
    - master
    - tags
  image: golang:1.13.1
  before_script:
    - apt-get update
    - apt-get install -y curl git zip
    - go mod download
    - go get "github.com/mitchellh/gox"
    - go get "github.com/inconshreveable/mousetrap"
  script:
    - ${GOPATH}/bin/gox -osarch="linux/amd64 windows/amd64" -output=./${ARTEFACT_FOLDER}/$CI_ENVIRONMENT_NAME/${CLI_NAME} -tags=$CI_ENVIRONMENT_NAME
    - cd ./${ARTEFACT_FOLDER}/$CI_ENVIRONMENT_NAME
    - tar -czf ${CLI_NAME}.tar.gz ${CLI_NAME}
    - zip ${CLI_NAME}.zip ${CLI_NAME}.exe
  artifacts:
    when: on_success
    paths:
      - ./${ARTEFACT_FOLDER}/$CI_ENVIRONMENT_NAME/${CLI_NAME}.zip
      - ./${ARTEFACT_FOLDER}/$CI_ENVIRONMENT_NAME/${CLI_NAME}.tar.gz

.portal-deployment:
  image: registry.gitlab.com/phoenixnap/platform-api/apigee-automation:0.0.6
  only:
    - master
  script:
    - /automation/upload_single_asset.py --file ./${ARTEFACT_FOLDER}/$CI_ENVIRONMENT_NAME/${CLI_NAME}.zip --portal "$APIGEE_PORTAL" --org $ORG_NAME --username $APIGEE_USER --password $APIGEE_PASSWORD
    - /automation/upload_single_asset.py --file ./${ARTEFACT_FOLDER}/$CI_ENVIRONMENT_NAME/${CLI_NAME}.tar.gz --portal "$APIGEE_PORTAL" --org $ORG_NAME --username $APIGEE_USER --password $APIGEE_PASSWORD

portal-dev-deploy:
  extends: .portal-deployment
  stage: dev-portal-deploy
  environment:
    name: dev

portal-prod-deploy:
  extends: .portal-deployment
  stage: prod-portal-deploy
  environment:
    name: prod
  only:
    - tags

build-dev:
  extends: .build
  stage: dev-build
  environment:
    name: dev

build-prod:
  extends: .build
  stage: prod-build
  environment:
    name: prod
  only:
    - tags
