# =====================================================
# Sample yaml config file; Rename and move to ~/pnap.yaml
# The CLI currently works without a version and can be left commented
# =====================================================

# Authentication
clientId:
clientSecret:

# Dev environment
hostname: https://phoenixnap-non-prod-ph-dev.apigee.net/api/bmc/v1/

# Local environment
#hostname: http://localhost:8081/bmc/v1/
timeout_secs: 10
