name: Release workflow

on:
  release:
    types:
      - created
      - edited

jobs:
  build-workflow:
    uses: phoenixnap/pnapctl/.github/workflows/build-workflow.yml

  build-artifacts:
    name: Build Artifacts
    needs:
      - unit-tests
      - component-tests
    runs-on: ubuntu-latest
    container: golang:1.17.1
    steps:
      - name: Install zip
        run: apt-get update && apt-get install -y zip
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Build and Pack
        run: make build-and-pack
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: build/dist

  publish-artifacts:
    name: Publish Release Assets
    needs:
      - build-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
      - name: Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/pnapctl-darwin-amd64.tar.gz
            dist/pnapctl-linux-amd64.tar.gz
            dist/pnapctl-windows-amd64.zip
