name: Build workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:1.17.1
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Go Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build
        run: make build
  
  unit-tests:
    runs-on: ubuntu-latest
    container: golang:1.17.1
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Go Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run tests
        run: make test-coverage
      - name: Publish Test Report
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always() # always run even if the previous step fails
        with:
          files: 'test/coverage/report.xml'